# Generated by Django 2.2.2 on 2020-04-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatmessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage', to='chat.ChatMessage'),
        ),
    ]
