# Generated by Django 2.2.2 on 2020-04-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200414_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatmessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='chat.ChatMessage', verbose_name='сообщения'),
        ),
    ]
