# Generated by Django 3.1.2 on 2020-10-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ссылка'),
        ),
    ]
